name = "Hugo Sassify"
license = "MIT"
licenselink = "https://github.com/yourusername/hugo-sassify-theme/blob/master/LICENSE"
description = "A modern Hugo theme for SaaS websites built with TailwindCSS"
homepage = "https://github.com/yourusername/hugo-sassify-theme"
tags = ["saas", "business", "tailwind", "responsive", "modern", "clean"]
features = ["responsive", "tailwind", "modern design"]
min_version = "0.80.0"

[author]
  name = "Your Name"
  homepage = "https://yourwebsite.com"
